return {
	Quirks = {
		Engine          = {Name = "Engine", Number = 0},
		HHHC            = {Name = "HHHC", Number = 1},
		OFA             = {Name = "OFA", Number = 2},
		Quirkless       = {Name = "Quirkless", Number = 3},
		ZeroGravity     = {Name = "Zero Gravity", Number = 4},
		Regeneration    = {Name = "Regeneration", Number = 5},
		Explosion       = {Name = "Explosion", Number = 6},
		Electric        = {Name = "Electric", Number = 7},
		WarpGate        = {Name = "Warp Gate", Number = 8},
		Gigantification = {Name = "Gigantification", Number = 9},
		Voice           = {Name = "Voice", Number = 10},
		AirProp         = {Name = "Air Prop", Number = 11},
		ShockAbsorp     = {Name = "Shock Absorption", Number = 12},
		DekuOFA         = {Name = "DekuOFA", Number = 13},
		Hardening       = {Name = "Hardening", Number = 14},
		HellFlame       = {Name = "HellFlame", Number = 15},
		Overhaul        = {Name = "Overhaul", Number = 16},
		Jet             = {Name = "Jet", Number = 17},
		BlackHole       = {Name = "Black Hole", Number = 18},
		Cremation       = {Name = "Cremation", Number = 19},
		DarkShadow      = {Name = "Dark Shadow", Number = 20},
		MuscleAugment   = {Name = "Muscle Augment", Number = 21},
		Permeation      = {Name = "Permeation", Number = 22},
		Popoff          = {Name = "Popoff", Number = 23},
		Somnam          = {Name = "Somnam", Number = 24},
		NavelLaser      = {Name = "Navel Laser", Number = 25},
		Decay           = {Name = "Decay", Number = 26},
		Acid            = {Name = "Acid", Number = 27},
		Creation        = {Name = "Creation", Number = 28},
		Clones          = {Name = "Clones", Number = 29},
		AllForOne       = {Name = "AllForOne", Number = 30},
		Tail            = {Name = "Tail", Number = 31},
		Frog            = {Name = "Frog", Number = 32},
		FierceWings     = {Name = "Fierce Wings", Number = 33},
		TomuraAFO       = {Name = "TomuraAFO", Number = 34},
		Orcinus         = {Name = "Orcinus", Number = 35},
		Manifest        = {Name = "Manifest", Number = 36},
		BigFist         = {Name = "Big Fist", Number = 37},
	}
}