return{
	["Engine"] = {number = 0},
	["Half Hot Half Cold"] = {number = 1},
	["One For All"] = {number = 2},
	["Quirkless"] = {number = 3},
	["Zero Gravity"] = {number = 4},
	["Regeneration"] = {number = 5},
	["Explosion"] = {number = 6},
	["Electric"] = {number = 7},
	["Warp Gate"] = {number = 8},
	["Gigantification"] = {number = 9},
	["Voice"] = {number = 10},
	["Air Propulsion"] = {number = 11},
	["Shock Absorption"] = {number = 12},
	["Deku One For All"] = {number = 13},
	["Hardening"] = {number = 14},
	["Hell Flame"] = {number = 15},
	["Overhaul"] = {number = 16},
	["Jet"] = {number = 17},
	["Black Hole"] = {number = 18},
	["Cremation"] = {number = 19},
	["Dark Shadow"] = {number = 20},
	["Muscle Augmentation"] = {number = 21},
	["Permeation"] = {number = 22},
	["Pop Off"] = {number = 23},
	["Somnambulist"] = {number = 24},
	["Navel Laser"] = {number = 25},
	["Decay"] = {number = 26},
	["Acid"] = {number = 27},
	["Creation"] = {number = 28},
	["Clones"] = {number = 29},
	["All For One"] = {number = 30},
	["Tail"] = {number = 31},
	["Frog"] = {number = 32},
	["Fierce Wings"] = {number = 33},
	["Tomura All For One"] = {number = 34},
	["Orcinus"] = {number = 35},
	["Manifest"] = {number = 36},
	["Big Fist"] = {number = 37}
}
